### ISSUE TITLE
Humidex ovwerflow in gauge-data.txt.tmpl

### ISSUE THREAD

**Issue by sangala** [mcrossley/SteelSeries-Weather-Gauges#9]
Computation humidex throw math overflow if dew point is negative in  gauge-data.txt.tmpl.
A one "if" more is necessary... compute humidex if dew point is > 1 (or bigger number) else humidex equals to outTemp.
## See: 2nd line and 3 last lines
# if $varExists('current.outTemp') and $current.outTemp.raw is not None and $varExists('current.dewpoint') and $current.dewpoint.raw is not None
# if ($current.outTemp.raw > 6) and ($current.dewpoint.raw > 6)

...
...
# else
# set $humidex = 'N/A'
# end if
# else

$humidex = $current.outTemp.raw
# end if

---

If temp is lower then 15°C humidex is not usually used…

**Comment by ghost** [comment]
The issue is that the humidex formula in the gauge-data.txt.tmpl template in the current release is flawed; it uses the current dewpoint in C or F (depending on what units you use in your database) when in fact the formula requires dewpoint to be in Kelvin (the overflow occurs when dewpoint gets very close to 0, positive or negative). I have submitted PR #8 to address this but it has not yet been actioned. If you look at PR #8 you see the chnages need to correct the formula (and a couple of other minor issue).

Gary

**Comment by mcrossley** [comment]
Should be fixed in teh v2.15.16 update 31 Oct 16

**Comment by sangala** [comment]
Thanks, the gjr80 commit works correctly. 
Note: in my use I have changed assignment 'N/A' to  $humidex and $apptemp to assign $current.outTemp.raw. Because if 'N/A' is there the sensors shows -20°C. I think, it is better to show current temperature in this case (if does not show an error).
